#
# base directory for model building
#
ROOT_DIR: '.'

#
# variablses that serve as identifiers
#
ID_VAR: ['ID']

#
# response variable
#
TARGET_VAR: 'target'


#
# Kaggle Submission Heaaders
#
KAGGLE_SUBMISSION_HEADERS: ['ID','PredictedProb']